# Generated by Django 5.2.1 on 2025-06-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagequeue',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
