# Generated by Django 5.2.1 on 2025-06-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_has_report'),
        ('message', '0002_messagequeue_failure_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagequeue',
            name='recipient',
        ),
        migrations.AddField(
            model_name='messagequeue',
            name='recipients',
            field=models.ManyToManyField(to='customers.customer'),
        ),
    ]
