# Generated by Django 5.2.1 on 2025-06-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_has_report'),
        ('message', '0003_remove_messagequeue_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagequeue',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('locked', '전송중'), ('sent', '전송완료'), ('failed', '전송실패')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='RecipientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('sent', '성공'), ('failed', '실패')], default='pending', max_length=16)),
                ('reason', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_statuses', to='message.messagequeue')),
            ],
        ),
    ]
