# Generated by Django 5.2.1 on 2025-06-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_messagequeue_status_recipientstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientstatus',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
