# Generated by Django 5.2.3 on 2025-06-10 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('call', '전화'), ('sms', '문자'), ('kakao', '카카오'), ('visit', '방문'), ('manual', '기타')], max_length=20)),
                ('purpose', models.CharField(choices=[('initial', '초회'), ('followup', '후속'), ('proposal', '제안'), ('contract', '청약'), ('support', '사후관리'), ('etc', '기타')], default='etc', max_length=30)),
                ('is_auto', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
