# Generated by Django 5.2.1 on 2025-06-01 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('14touch', '14터치'), ('콜', '콜'), ('방문', '방문'), ('파싱', '파싱'), ('기타', '기타')], max_length=16)),
                ('content', models.TextField()),
                ('strategy_note', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('underwriting_status', models.CharField(blank=True, max_length=16)),
                ('underwriting_result', models.TextField(blank=True)),
                ('insurance_products', models.TextField(blank=True)),
                ('touched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
