# Generated by Django 5.2.1 on 2025-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touchlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='touchlog',
            old_name='insurance_products',
            new_name='memo',
        ),
        migrations.RemoveField(
            model_name='touchlog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='touchlog',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='touchlog',
            name='strategy_note',
        ),
        migrations.RemoveField(
            model_name='touchlog',
            name='touched_at',
        ),
        migrations.RemoveField(
            model_name='touchlog',
            name='type',
        ),
        migrations.RemoveField(
            model_name='touchlog',
            name='underwriting_result',
        ),
        migrations.RemoveField(
            model_name='touchlog',
            name='underwriting_status',
        ),
        migrations.AddField(
            model_name='touchlog',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='touchlog',
            name='method',
            field=models.CharField(choices=[('call', '전화'), ('sms', '문자'), ('kakao', '카카오'), ('visit', '방문'), ('manual', '기타')], default='manual', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touchlog',
            name='purpose',
            field=models.CharField(choices=[('initial', '초회'), ('followup', '후속'), ('proposal', '제안'), ('contract', '청약'), ('support', '사후관리'), ('etc', '기타')], default='etc', max_length=30),
        ),
    ]
