# Generated by Django 5.2.1 on 2025-05-30 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('monthly_cpc_goal', models.IntegerField(default=0)),
                ('weekly_cpc_goal', models.IntegerField(default=0)),
                ('daily_call_1min', models.IntegerField(default=0)),
                ('daily_call_2min', models.IntegerField(default=0)),
                ('weekly_call_2min', models.IntegerField(default=0)),
                ('daily_proposals', models.IntegerField(default=0)),
                ('daily_visit_proposals', models.IntegerField(default=0)),
                ('daily_band_verified', models.IntegerField(default=0)),
                ('daily_prospective_secure', models.IntegerField(default=0)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
