# Generated by Django 5.2.1 on 2025-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='weekly_call_1min',
            field=models.IntegerField(default=0),
        ),
    ]
