# Generated by Django 5.2.1 on 2025-06-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_strategy_weekly_call_1min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='daily_prospective_secure',
            new_name='daily_grade_potential',
        ),
    ]
