# Generated by Django 5.2.1 on 2025-06-01 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('region', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone_encrypted', models.CharField(max_length=64)),
                ('birth_encrypted', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=1)),
                ('attribute', models.CharField(blank=True, choices=[('인콜', '인콜'), ('카드', '카드'), ('멤버스', '멤버스'), ('소개', '소개'), ('지인', '지인'), ('가족', '가족')], max_length=16)),
                ('grade', models.CharField(blank=True, choices=[('충성', '충성'), ('가망', '가망'), ('유령', '유령'), ('미가망', '미가망')], max_length=16)),
                ('propensity', models.CharField(blank=True, choices=[('니즈확실', '니즈확실'), ('정보위주', '정보위주'), ('친밀위주', '친밀위주')], max_length=16)),
                ('intimacy', models.CharField(blank=True, choices=[('친함', '친함'), ('중립', '중립'), ('경계', '경계')], max_length=16)),
                ('priority', models.CharField(blank=True, choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=16)),
                ('is_target_customer', models.BooleanField(default=False)),
                ('is_active_touching', models.BooleanField(default=False)),
                ('sent_business_card', models.BooleanField(default=False)),
                ('sent_report', models.BooleanField(default=False)),
                ('sent_pre_call_sms', models.BooleanField(default=False)),
                ('first_call_done', models.BooleanField(default=False)),
                ('sent_proposal_on_reject', models.BooleanField(default=False)),
                ('second_call_done', models.BooleanField(default=False)),
                ('suggested_visit', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
