# Generated by Django 5.2.1 on 2025-06-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_touch_step',
            field=models.CharField(choices=[('report', '리포트 발송'), ('pre_sms', '콜 전 문자'), ('call1', '1차 콜'), ('reject_sms', '거절 후 제안'), ('call2', '2차 콜'), ('visit', '방문 제안'), ('done', '완료')], default='report', help_text='현재 고객의 접촉 단계', max_length=20),
        ),
    ]
