# Generated by Django 5.2.1 on 2025-06-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_current_touch_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_call_done',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='second_call_done',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sent_business_card',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sent_pre_call_sms',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sent_proposal_on_reject',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sent_report',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='suggested_visit',
        ),
    ]
