# Generated by Django 5.2.1 on 2025-06-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_first_call_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_report',
            field=models.BooleanField(default=False, help_text='리포트 등록 여부'),
        ),
    ]
