# Generated by Django 5.2.3 on 2025-06-10 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStandardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_call_1min', models.IntegerField(default=0)),
                ('daily_call_2min', models.IntegerField(default=0)),
                ('daily_grade_potential', models.IntegerField(default=0)),
                ('daily_band_verified', models.IntegerField(default=0)),
                ('daily_proposals', models.IntegerField(default=0)),
                ('daily_visit_proposals', models.IntegerField(default=0)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
