# Generated by Django 5.2.1 on 2025-06-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailystandardactivity',
            old_name='band_verified',
            new_name='daily_band_verified',
        ),
        migrations.RenameField(
            model_name='dailystandardactivity',
            old_name='call_1min',
            new_name='daily_call_1min',
        ),
        migrations.RenameField(
            model_name='dailystandardactivity',
            old_name='call_2min',
            new_name='daily_call_2min',
        ),
        migrations.RenameField(
            model_name='dailystandardactivity',
            old_name='grade_potential',
            new_name='daily_grade_potential',
        ),
    ]
